/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myErc1155Sol from './MyERC1155.sol/index.js';
export type { myErc1155Sol };
import type * as myErc20Sol from './MyERC20.sol/index.js';
export type { myErc20Sol };
import type * as myErc721Sol from './MyERC721.sol/index.js';
export type { myErc721Sol };
export type { LootBox } from './LootBox.js';