/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface LootBoxInterface extends Interface {
    getFunction(nameOrSignature: "ERC1155_AMOUNT" | "ERC1155_ID" | "ERC20_AMOUNT" | "FEE" | "TOTAL_WEIGHT" | "WEIGHTS" | "openBox" | "owner" | "renounceOwnership" | "rewardERC1155Address" | "rewardERC20Address" | "rewardERC721Address" | "transferOwnership" | "userRewards" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BoxOpened" | "OwnershipTransferred" | "RandomNumberGenerated" | "RewardIssued" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'ERC1155_AMOUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'ERC1155_ID', values?: undefined): string;
encodeFunctionData(functionFragment: 'ERC20_AMOUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'TOTAL_WEIGHT', values?: undefined): string;
encodeFunctionData(functionFragment: 'WEIGHTS', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'openBox', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardERC1155Address', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardERC20Address', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardERC721Address', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userRewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'ERC1155_AMOUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ERC1155_ID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ERC20_AMOUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TOTAL_WEIGHT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WEIGHTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openBox', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardERC1155Address', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardERC20Address', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardERC721Address', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace BoxOpenedEvent {
      export type InputTuple = [user: AddressLike, fee: BigNumberish];
      export type OutputTuple = [user: string, fee: bigint];
      export interface OutputObject {user: string, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RandomNumberGeneratedEvent {
      export type InputTuple = [user: AddressLike, randomNumber: BigNumberish];
      export type OutputTuple = [user: string, randomNumber: bigint];
      export interface OutputObject {user: string, randomNumber: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardIssuedEvent {
      export type InputTuple = [user: AddressLike, rewardType: BigNumberish, rewardValue: BigNumberish];
      export type OutputTuple = [user: string, rewardType: bigint, rewardValue: bigint];
      export interface OutputObject {user: string, rewardType: bigint, rewardValue: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, amount: bigint];
      export interface OutputObject {owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LootBox extends BaseContract {
    
    connect(runner?: ContractRunner | null): LootBox;
    waitForDeployment(): Promise<this>;

    interface: LootBoxInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ERC1155_AMOUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ERC1155_ID: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ERC20_AMOUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TOTAL_WEIGHT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WEIGHTS: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    openBox: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rewardERC1155Address: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rewardERC20Address: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rewardERC721Address: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    userRewards: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint] & {randomNumber: bigint, rewardType: bigint, rewardValue: bigint }],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ERC1155_AMOUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ERC1155_ID'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ERC20_AMOUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TOTAL_WEIGHT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WEIGHTS'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'openBox'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardERC1155Address'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rewardERC20Address'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rewardERC721Address'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userRewards'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint] & {randomNumber: bigint, rewardType: bigint, rewardValue: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BoxOpened'): TypedContractEvent<BoxOpenedEvent.InputTuple, BoxOpenedEvent.OutputTuple, BoxOpenedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RandomNumberGenerated'): TypedContractEvent<RandomNumberGeneratedEvent.InputTuple, RandomNumberGeneratedEvent.OutputTuple, RandomNumberGeneratedEvent.OutputObject>;
getEvent(key: 'RewardIssued'): TypedContractEvent<RewardIssuedEvent.InputTuple, RewardIssuedEvent.OutputTuple, RewardIssuedEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'BoxOpened(address,uint256)': TypedContractEvent<BoxOpenedEvent.InputTuple, BoxOpenedEvent.OutputTuple, BoxOpenedEvent.OutputObject>;
      BoxOpened: TypedContractEvent<BoxOpenedEvent.InputTuple, BoxOpenedEvent.OutputTuple, BoxOpenedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RandomNumberGenerated(address,uint256)': TypedContractEvent<RandomNumberGeneratedEvent.InputTuple, RandomNumberGeneratedEvent.OutputTuple, RandomNumberGeneratedEvent.OutputObject>;
      RandomNumberGenerated: TypedContractEvent<RandomNumberGeneratedEvent.InputTuple, RandomNumberGeneratedEvent.OutputTuple, RandomNumberGeneratedEvent.OutputObject>;
    

      'RewardIssued(address,uint8,uint256)': TypedContractEvent<RewardIssuedEvent.InputTuple, RewardIssuedEvent.OutputTuple, RewardIssuedEvent.OutputObject>;
      RewardIssued: TypedContractEvent<RewardIssuedEvent.InputTuple, RewardIssuedEvent.OutputTuple, RewardIssuedEvent.OutputObject>;
    

      'Withdraw(address,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }