/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myErc1155Sol from './MyERC1155.sol/index.js';
export * as myErc20Sol from './MyERC20.sol/index.js';
export * as myErc721Sol from './MyERC721.sol/index.js';
export { LootBox__factory } from './LootBox__factory.js';