/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswapPermitSwapSol from "./UniswapPermitSwap.sol";
export type { uniswapPermitSwapSol };
export type { Lock } from "./Lock";
export type { UniswapPermit2Swap } from "./UniswapPermit2Swap";
