/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LudoGameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "currentGameState"
      | "currentTurn"
      | "gameId"
      | "gamePlayers"
      | "gameWinner"
      | "getCurrentGameInfo"
      | "getGamePlayers"
      | "getPlayerInfo"
      | "getWinner"
      | "players"
      | "registerPlayer"
      | "rollDice"
      | "stakeAmount"
      | "stakingToken"
      | "totalStaked"
      | "turnIndex"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DiceRolled"
      | "GameFinished"
      | "GameStarted"
      | "PlayerMoved"
      | "PlayerRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "currentGameState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentTurn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gameId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gamePlayers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentGameInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGamePlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerInfo",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "players",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPlayer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "rollDice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "stakeAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "turnIndex",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentGameState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentTurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gamePlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameWinner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentGameInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGamePlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWinner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "players", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rollDice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "turnIndex", data: BytesLike): Result;
}

export namespace DiceRolledEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    diceValue: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, player: string, diceValue: bigint];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    diceValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameFinishedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    winner: AddressLike,
    totalPrize: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    winner: string,
    totalPrize: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    winner: string;
    totalPrize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameStartedEvent {
  export type InputTuple = [gameId: BigNumberish, players: AddressLike[]];
  export type OutputTuple = [gameId: bigint, players: string[]];
  export interface OutputObject {
    gameId: bigint;
    players: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerMovedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    newPosition: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    player: string,
    newPosition: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    newPosition: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerRegisteredEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    name: string,
    color: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    player: string,
    name: string,
    color: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    name: string;
    color: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LudoGame extends BaseContract {
  connect(runner?: ContractRunner | null): LudoGame;
  waitForDeployment(): Promise<this>;

  interface: LudoGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentGameState: TypedContractMethod<[], [bigint], "view">;

  currentTurn: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  gameId: TypedContractMethod<[], [bigint], "view">;

  gamePlayers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  gameWinner: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getCurrentGameInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, string, bigint] & {
        currentGameId: bigint;
        state: bigint;
        playersCount: bigint;
        currentPlayer: string;
        staked: bigint;
      }
    ],
    "view"
  >;

  getGamePlayers: TypedContractMethod<
    [_gameId: BigNumberish],
    [string[]],
    "view"
  >;

  getPlayerInfo: TypedContractMethod<
    [_gameId: BigNumberish, _player: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        name: string;
        color: bigint;
        score: bigint;
        position: bigint;
        isRegistered: boolean;
      }
    ],
    "view"
  >;

  getWinner: TypedContractMethod<[_gameId: BigNumberish], [string], "view">;

  players: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, string, bigint, bigint, boolean, bigint] & {
        playerAddress: string;
        name: string;
        color: bigint;
        score: bigint;
        isRegistered: boolean;
        position: bigint;
      }
    ],
    "view"
  >;

  registerPlayer: TypedContractMethod<
    [_name: string, _color: BigNumberish],
    [void],
    "nonpayable"
  >;

  rollDice: TypedContractMethod<[], [bigint], "nonpayable">;

  stakeAmount: TypedContractMethod<[], [bigint], "view">;

  stakingToken: TypedContractMethod<[], [string], "view">;

  totalStaked: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  turnIndex: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentGameState"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentTurn"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "gameId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gamePlayers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "gameWinner"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentGameInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, string, bigint] & {
        currentGameId: bigint;
        state: bigint;
        playersCount: bigint;
        currentPlayer: string;
        staked: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGamePlayers"
  ): TypedContractMethod<[_gameId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPlayerInfo"
  ): TypedContractMethod<
    [_gameId: BigNumberish, _player: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        name: string;
        color: bigint;
        score: bigint;
        position: bigint;
        isRegistered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinner"
  ): TypedContractMethod<[_gameId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "players"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, string, bigint, bigint, boolean, bigint] & {
        playerAddress: string;
        name: string;
        color: bigint;
        score: bigint;
        isRegistered: boolean;
        position: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerPlayer"
  ): TypedContractMethod<
    [_name: string, _color: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rollDice"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakingToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "turnIndex"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "DiceRolled"
  ): TypedContractEvent<
    DiceRolledEvent.InputTuple,
    DiceRolledEvent.OutputTuple,
    DiceRolledEvent.OutputObject
  >;
  getEvent(
    key: "GameFinished"
  ): TypedContractEvent<
    GameFinishedEvent.InputTuple,
    GameFinishedEvent.OutputTuple,
    GameFinishedEvent.OutputObject
  >;
  getEvent(
    key: "GameStarted"
  ): TypedContractEvent<
    GameStartedEvent.InputTuple,
    GameStartedEvent.OutputTuple,
    GameStartedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerMoved"
  ): TypedContractEvent<
    PlayerMovedEvent.InputTuple,
    PlayerMovedEvent.OutputTuple,
    PlayerMovedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerRegistered"
  ): TypedContractEvent<
    PlayerRegisteredEvent.InputTuple,
    PlayerRegisteredEvent.OutputTuple,
    PlayerRegisteredEvent.OutputObject
  >;

  filters: {
    "DiceRolled(uint256,address,uint256)": TypedContractEvent<
      DiceRolledEvent.InputTuple,
      DiceRolledEvent.OutputTuple,
      DiceRolledEvent.OutputObject
    >;
    DiceRolled: TypedContractEvent<
      DiceRolledEvent.InputTuple,
      DiceRolledEvent.OutputTuple,
      DiceRolledEvent.OutputObject
    >;

    "GameFinished(uint256,address,uint256)": TypedContractEvent<
      GameFinishedEvent.InputTuple,
      GameFinishedEvent.OutputTuple,
      GameFinishedEvent.OutputObject
    >;
    GameFinished: TypedContractEvent<
      GameFinishedEvent.InputTuple,
      GameFinishedEvent.OutputTuple,
      GameFinishedEvent.OutputObject
    >;

    "GameStarted(uint256,address[])": TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;
    GameStarted: TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;

    "PlayerMoved(uint256,address,uint256)": TypedContractEvent<
      PlayerMovedEvent.InputTuple,
      PlayerMovedEvent.OutputTuple,
      PlayerMovedEvent.OutputObject
    >;
    PlayerMoved: TypedContractEvent<
      PlayerMovedEvent.InputTuple,
      PlayerMovedEvent.OutputTuple,
      PlayerMovedEvent.OutputObject
    >;

    "PlayerRegistered(uint256,address,string,uint8)": TypedContractEvent<
      PlayerRegisteredEvent.InputTuple,
      PlayerRegisteredEvent.OutputTuple,
      PlayerRegisteredEvent.OutputObject
    >;
    PlayerRegistered: TypedContractEvent<
      PlayerRegisteredEvent.InputTuple,
      PlayerRegisteredEvent.OutputTuple,
      PlayerRegisteredEvent.OutputObject
    >;
  };
}
