/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'LootBox', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LootBox__factory>
getContractFactory(name: 'RewardERC1155', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RewardERC1155__factory>
getContractFactory(name: 'RewardERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RewardERC20__factory>
getContractFactory(name: 'RewardERC721', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RewardERC721__factory>
getContractFactory(name: 'LootBoxTest', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LootBoxTest__factory>

  getContractAt(name: 'LootBox', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LootBox>
getContractAt(name: 'RewardERC1155', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RewardERC1155>
getContractAt(name: 'RewardERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RewardERC20>
getContractAt(name: 'RewardERC721', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RewardERC721>
getContractAt(name: 'LootBoxTest', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LootBoxTest>

  deployContract(name: 'LootBox', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LootBox>
deployContract(name: 'RewardERC1155', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardERC1155>
deployContract(name: 'RewardERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardERC20>
deployContract(name: 'RewardERC721', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardERC721>
deployContract(name: 'LootBoxTest', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LootBoxTest>

  deployContract(name: 'LootBox', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LootBox>
deployContract(name: 'RewardERC1155', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardERC1155>
deployContract(name: 'RewardERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardERC20>
deployContract(name: 'RewardERC721', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardERC721>
deployContract(name: 'LootBoxTest', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LootBoxTest>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  