/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from './contracts/index.js';
export type { contracts };
import type * as test from './test/index.js';
export type { test };
export * as factories from './factories/index.js';
export type { LootBox } from './contracts/LootBox.js';
export { LootBox__factory } from './factories/contracts/LootBox__factory.js';
export type { RewardERC1155 } from './contracts/MyERC1155.sol/RewardERC1155.js';
export { RewardERC1155__factory } from './factories/contracts/MyERC1155.sol/RewardERC1155__factory.js';
export type { RewardERC20 } from './contracts/MyERC20.sol/RewardERC20.js';
export { RewardERC20__factory } from './factories/contracts/MyERC20.sol/RewardERC20__factory.js';
export type { RewardERC721 } from './contracts/MyERC721.sol/RewardERC721.js';
export { RewardERC721__factory } from './factories/contracts/MyERC721.sol/RewardERC721__factory.js';
export type { LootBoxTest } from './test/Lootbox.sol/LootBoxTest.js';
export { LootBoxTest__factory } from './factories/test/Lootbox.sol/LootBoxTest__factory.js';