/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ludoGameSol from "./LudoGame.sol";
export type { ludoGameSol };
export type { Lock } from "./Lock";
export type { MockERC20 } from "./MockERC20";
