/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoNftSol from "./DaoNft.sol";
export type { daoNftSol };
import type * as erc7432RoleSol from "./ERC7432Role.sol";
export type { erc7432RoleSol };
import type * as gatedDaoSol from "./GatedDao.sol";
export type { gatedDaoSol };
